# Generated by Django 4.2.6 on 2023-10-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=30)),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
