# Generated by Django 4.2.6 on 2023-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red')], max_length=50, null=True),
        ),
    ]
